FROM registry.ci.openshift.org/ocp/builder:rhel-9-golang-1.22-openshift-4.17 AS builder
WORKDIR /src/ovirt-csi-driver
COPY . .
RUN make build

FROM registry.ci.openshift.org/ocp/4.17:base-rhel9

RUN yum install -y e2fsprogs xfsprogs
COPY --from=builder /src/ovirt-csi-driver/bin/ovirt-csi-driver .

ENTRYPOINT ["./ovirt-csi-driver"]
